# Generated by Django 3.1 on 2020-08-22 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Netflix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mopsn/images')),
                ('description', models.TextField(blank=True, null=True)),
                ('price_paypal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_btc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lang', models.CharField(blank=True, max_length=100)),
                ('publish_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('sold', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ps4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='mopsn/images')),
                ('price_paypal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_btc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('region_code', models.IntegerField(blank=True, null=True)),
                ('region_country', models.CharField(blank=True, max_length=30)),
                ('publish_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('sold', models.BooleanField(default=False)),
            ],
        ),
    ]
