# Generated by Django 3.1 on 2020-08-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mopsn', '0003_netflix1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Netflix1',
        ),
    ]
