# Generated by Django 3.1 on 2020-08-24 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mopsn', '0004_auto_20200824_1835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nety',
        ),
    ]
